name: GitHub Pages
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn nx build pokemon-card-maker
    - name: Deploy
      run: yarn nx deploy pokemon-card-maker --base-href=https://jad31.github.io/pokemon-card-maker/
